# camera79
image_width: 1920
image_height: 1536
camera_name: camera2
camera_matrix:
  rows: 3
  cols: 3
  data: [991.8157 ,   0.     , 958.01288,
           0.     , 992.26888, 752.14558,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.269058, 0.045261, 0.001263, -0.000425, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [991.8157 ,   0.     , 958.01288,   0.     ,
           0.     , 992.26888, 752.14558,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]