image_width: 1920
image_height: 1536
camera_name: camera08
camera_matrix:
  rows: 3
  cols: 3
  data: [980.64685,   0.     , 956.51558,
           0.     , 987.3307 , 776.95868,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.269953, 0.046971, -0.001743, 0.001197, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [980.64685,   0.     , 956.51558,   0.     ,
           0.     , 987.3307 , 776.95868,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]